version: "3.8"

services:
    front:
        image: node:18-alpine
        working_dir: /app
        ports:
            - "5173:5173"
        volumes:
            - ./front:/app
            - /app/node_modules
        command: sh -c "npm install && npm run dev"
        depends_on:
            - back

    back:
        image: node:18-alpine
        working_dir: /app
        ports:
            - "3000:3000"
        volumes:
            - ./back:/app
            - /app/node_modules
            - ./back/.env:/app/.env
        environment:
            - MONGO_URI=mongodb+srv://hackathon:Lb4c1seSfMmpspYR@cluster0.n1qsqdw.mongodb.net/hackathon?retryWrites=true&w=majority&appName=Cluster0
        command: sh -c "npm install && npm run dev"
